"""
Builds the self-hosted web fonts: subset + sliced woff2 files (Google-Fonts style `unicode-range` slices), so a player on a
slow connection (or where fonts.googleapis.com is blocked) only downloads the few slices a screen really needs, and nothing
blocks the first paint.

  pip install fonttools brotli
  python tools/fonts/build.py

Inputs (downloaded into tools/fonts/.cache on first run, SIL OFL licensed):
  Noto Serif SC (variable, instanced at 700 and 900) · Ma Shan Zheng (brush headings)
Outputs: packages/client/public/fonts/*.woff2 and packages/client/src/styles/fonts.css
Body text uses the system CJK fonts (PingFang SC / Microsoft YaHei / Noto Sans CJK): zero download.
"""
from __future__ import annotations

import collections
import os
import re
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[2]
CACHE = Path(os.environ.get('FONT_CACHE', ROOT / 'tools/fonts/.cache'))
OUT = ROOT / 'packages/client/public/fonts'
CSS = ROOT / 'packages/client/src/styles/fonts.css'
SRC = ROOT / 'packages'
SLICE = 230  # characters per slice after the first

SOURCES = {
    'NotoSerifSC.ttf': 'https://github.com/google/fonts/raw/main/ofl/notoserifsc/NotoSerifSC%5Bwght%5D.ttf',
    'MaShanZheng-Regular.ttf': 'https://github.com/google/fonts/raw/main/ofl/mashanzheng/MaShanZheng-Regular.ttf',
}
# family, css weight, file, variable weight to instance (None = static font)
FACES = [
    ('Noto Serif SC', 700, 'NotoSerifSC.ttf', 700),
    ('Noto Serif SC', 900, 'NotoSerifSC.ttf', 900),
    ('Ma Shan Zheng', 400, 'MaShanZheng-Regular.ttf', None),
]

CJK = re.compile(r'[‐-›←-⇿≠-≥·×　-〿一-鿿＀-￯]')


def collect() -> list[str]:
    """Every non-ASCII character the game can show, most important first (screens, card names, card texts, server messages)."""
    weight: collections.Counter[str] = collections.Counter()
    for path in SRC.rglob('*'):
        if path.suffix not in {'.ts', '.tsx', '.css'} or 'node_modules' in path.parts or 'dist' in path.parts or 'test' in path.parts:
            continue
        text = path.read_text(encoding='utf-8', errors='ignore')
        bonus = 4 if 'client/src/screens' in path.as_posix() or 'client\\src\\screens' in str(path) else 1
        for ch in CJK.findall(text):
            weight[ch] += bonus
    return [c for c, _ in weight.most_common()]


def ranges(codes: list[int]) -> str:
    codes = sorted(set(codes))
    out, start, prev = [], codes[0], codes[0]
    for c in codes[1:] + [None]:
        if c is not None and c == prev + 1:
            prev = c
            continue
        out.append(f'U+{start:X}' if start == prev else f'U+{start:X}-{prev:X}')
        if c is not None:
            start = prev = c
    return ','.join(out)


def fetch(name: str) -> Path:
    CACHE.mkdir(parents=True, exist_ok=True)
    p = CACHE / name
    if not p.exists():
        print('downloading', name)
        urllib.request.urlretrieve(SOURCES[name], p)
    return p


def make_slice(font_path: Path, text: str, out: Path) -> int:
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['kern']
    opts.hinting = False
    opts.desubroutinize = True
    opts.notdef_outline = False
    opts.name_IDs = [1, 2]
    opts.drop_tables += ['DSIG']
    f = subset.load_font(str(font_path), opts)
    s = subset.Subsetter(opts)
    s.populate(text=text)
    s.subset(f)
    subset.save_font(f, str(out), opts)
    return out.stat().st_size


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    chars = collect()
    ascii_chars = ''.join(chr(c) for c in range(0x20, 0x7F))
    # slice 0: Latin + punctuation + the most used characters (what the title screen and lobby need)
    first = ascii_chars + ''.join(chars[:160])
    slices = [first] + [''.join(chars[i:i + SLICE]) for i in range(160, len(chars), SLICE)]
    print(f'{len(chars)} distinct characters → {len(slices)} slices')

    css = ['/* Generated by tools/fonts/build.py — do not edit. Self-hosted subsets of Noto Serif SC and Ma Shan Zheng (SIL OFL). */']
    total = 0
    for family, weight, fname, wght in FACES:
        src = fetch(fname)
        if wght is not None:
            inst = CACHE / f'{src.stem}-{wght}.ttf'
            if not inst.exists():
                print('instancing', family, wght)
                vf = TTFont(str(src))
                instancer.instantiateVariableFont(vf, {'wght': wght}, inplace=True)
                vf.save(str(inst))
            src = inst
        tag = family.lower().replace(' ', '-')
        for i, text in enumerate(slices):
            name = f'{tag}-{weight}-{i}.woff2'
            size = make_slice(src, text, OUT / name)
            total += size
            codes = [ord(c) for c in text]
            css.append(
                f"@font-face {{ font-family: '{family}'; font-weight: {weight}; font-style: normal; font-display: swap; "
                f"src: url(/fonts/{name}) format('woff2'); unicode-range: {ranges(codes)}; }}"
            )
        print(f'{family} {weight}: done')
    CSS.write_text('\n'.join(css) + '\n', encoding='utf-8')
    print(f'{total / 1024:.0f} KB of font data in total (a screen only fetches the slices it needs)')


if __name__ == '__main__':
    main()
