import type { EventCardDef } from './types.js';

const e = (d: Omit<EventCardDef, 'kind' | 'shape'> & { shape?: EventCardDef['shape'] }): EventCardDef => ({
  kind: 'event',
  shape: d.down === undefined ? 'none' : 'dual',
  ...d,
});

export const EVENT_CARDS: EventCardDef[] = [
  // ── 双向事件 ─────────────────────────────────────
  e({ id: 'new_ip', name: '新IP流行', count: 3, topic: '社会',
    up: '社群规模-3。', down: '所有玩家抽一张行动牌，社群规模-1。' }),
  e({ id: 'headline', name: '新闻头条报道东方', count: 2, topic: '社会',
    up: '社群规模+2。', down: '社群规模-3。' }),
  e({ id: 'shipping_loss', name: '物流损耗', count: 1, topic: '创作',
    up: '抽一张行动牌，个人影响力-1。', down: '个人影响力-2。' }),
  e({ id: 'site_closed', name: '东方主题网站倒闭', count: 3, topic: '社群',
    up: '所有玩家弃一张手牌。社群规模-2。', down: '弃两张手牌。社群规模+2，个人影响力+1。' }),
  e({ id: 'breakthrough', name: '项目取得突破性进展', count: 1, topic: '创作',
    up: '抽两张行动牌。', down: '弃置一张手牌，个人影响力+2。' }),
  e({ id: 'national_event', name: '全国性活动', count: 3, topic: '活动',
    up: '社群规模+2。', down: '社群规模-1，个人影响力-1。' }),
  e({ id: 'site_founded', name: '东方主题网站建立', count: 3, topic: '社群',
    up: '每位玩家抽一张行动牌。社群规模+1。', down: '社群规模-1。' }),
  e({ id: 'pirated', name: '作品遭到盗版', count: 1, topic: '创作',
    up: '弃两张手牌，个人影响力+1，社群规模+2。', down: '弃一张手牌，个人影响力+2，社群规模-1。' }),
  e({ id: 'zun_visit', name: 'ZUN首次来华', count: 1, topic: '官方',
    up: '社群规模+3。', down: '社群规模-1。' }),
  e({ id: 'elitism', name: '精英化思潮', count: 1, topic: '社群',
    up: '所有个人影响力小于3的玩家弃一张手牌。', down: '所有个人影响力大于2的玩家弃一张手牌。' }),
  e({ id: 'pirate_game', name: '盗版游戏使用了东方素材', count: 1, topic: '社会',
    up: '社群规模+3，个人影响力-2。', down: '社群规模+1，个人影响力+1。' }),
  e({ id: 'collab', name: '知名IP与东方进行联动', count: 1, topic: '官方',
    up: '社群规模+3。', down: '社群规模+1。' }),
  e({ id: 'fake_peace', name: '迫真和解', count: 1, topic: '社群',
    up: '抽一张行动牌，社群规模+1。', down: '社群规模-1。' }),
  e({ id: 'bad_remark', name: '著名作者发表不当言论', count: 1, topic: '社会',
    up: '社群规模-5。', down: '社群规模-1。' }),
  e({ id: 'cited', name: '作品被引用', count: 1, topic: '创作',
    up: '个人影响力+2。', down: '每位其他玩家依次将一张手牌交付给你。' }),
  e({ id: 'big_update', name: '一线同人大作更新', count: 1, topic: '社群',
    up: '所有玩家个人影响力-1，社群规模+3。', down: '社群规模-2。' }),
  e({ id: 'upset', name: '下克上', count: 1, topic: '创作',
    up: '弃一张手牌，个人影响力+1。', down: '抽一张行动牌，个人影响力-1。' }),
  e({ id: 'police_outbreak', name: '东方警察爆发', count: 1, topic: '社群',
    up: '其他玩家弃一张手牌。社群规模-2。', down: '社群规模-5，个人影响力-3。' }),
  e({ id: 'investigated', name: '活动或作品被调查', count: 1, topic: '社会',
    up: '社群规模-3。', down: '社群规模-1。' }),
  e({ id: 'third_contact', name: '第三类接触', count: 1, topic: '官方',
    up: '个人影响力+1。', down: '社群规模-1，个人影响力-1。' }),
  e({ id: 'mass_flame', name: '大规模撕逼', count: 1, topic: '社群',
    up: '社群规模-3，个人影响力+3。', down: '社群规模-1，个人影响力-1。' }),
  e({ id: 'property_loss', name: '蒙受财产损失', count: 1, topic: '个人',
    up: '弃两张手牌。', down: '个人影响力-1。' }),
  e({ id: 'discord', name: '与成员不和', count: 1, topic: '创作',
    up: '弃一张手牌。', down: '个人影响力-1。' }),
  e({ id: 'kids_influx', name: '熊孩子涌入', count: 1, topic: '社群',
    up: '所有玩家个人影响力-1。', down: '社群规模+1。' }),
  e({ id: 'new_trend', name: '圈内新流行', count: 1, topic: '社群',
    up: '社群规模+2。', down: '社群规模-1。' }),
  e({ id: 'creative_wave', name: '新的创作浪潮', count: 1, topic: '创作',
    up: '社群规模+3，个人影响力+1。', down: '社群规模+1，个人影响力+3。' }),
  e({ id: 'intl_exchange', name: '国际交流', count: 1, topic: '社群',
    up: '社群规模+3。', down: '社群规模+1，抽一张行动牌。' }),
  e({ id: 'customs', name: '海关严查', count: 1, topic: '社会',
    up: '社群规模-2。', down: '弃一张手牌。' }),
  e({ id: 'zun_ban', name: 'ZUN新规约：禁止', count: 1, topic: '官方',
    up: '由你开始，每位玩家选择一张行动牌交付给右边的玩家。', down: '每位玩家弃一张手牌。' }),
  e({ id: 'expelled', name: '开除圈籍', count: 1, topic: '社群',
    up: '社群规模增加你个人影响力的绝对值。', down: '社群规模减少你个人影响力的绝对值。' }),
  e({ id: 'big_release', name: '进行重大发布', count: 1, topic: '创作',
    up: '个人影响力+1。', down: '选择弃置X张手牌，个人影响力+X。' }),
  e({ id: 'postponed', name: '线下活动延期', count: 1, topic: '活动',
    up: '每位玩家弃一张手牌，社群规模-3。', down: '弃两张手牌。' }),
  e({ id: 'plagiarism', name: '合作作者被指证抄袭', count: 1, topic: '创作',
    up: '弃一张手牌，个人影响力-1。', down: '弃两张手牌。' }),
  e({ id: 'writers_block', name: '作品难产', count: 1, topic: '创作',
    up: '个人影响力-2。', down: '弃两张手牌。' }),
  e({ id: 'zun_riddle', name: 'ZUN的迷之发言', count: 1, topic: '官方',
    up: '由你开始，每位玩家选择左边玩家的一张手牌，并将其加入自己的手牌。', down: '社群规模-1。' }),
  e({ id: 'circle_union', name: '建立社团联合组织', count: 1, topic: '社群',
    up: '个人影响力+1。每位其他玩家将一张手牌交付给你，你从手牌中选取与以此方式获得的手牌数量等量的手牌，按任意顺序放回行动牌堆顶，然后所有其他玩家依次抽一张行动牌。',
    down: '个人影响力+1，弃两张手牌，然后抽两张行动牌。' }),
  e({ id: 'zun_frontier', name: 'ZUN新规约：新领域', count: 1, topic: '官方',
    up: '由你开始，每位玩家抽一张行动牌。', down: '查看行动牌堆顶的两张牌，选一张加入你的手牌，另一张加入指定玩家的手牌。' }),
  e({ id: 'local_event', name: '地方性活动', count: 1, topic: '活动',
    up: '从你的上一位玩家开始，你和与你相邻的玩家依次抽一张行动牌。社群规模+1。',
    down: '从你的上一位玩家开始，你和与你相邻的玩家依次弃一张手牌。社群规模-1。' }),
  e({ id: 'spotlight', name: '备受瞩目', count: 1, topic: '社群',
    up: '直到你的下个回合开始，你的个人影响力锁定为2。本事件牌在你的下回合开始阶段时进入弃牌堆。',
    down: '直到你的下个回合开始，你的个人影响力等同于你的手牌数。本事件牌在你的下回合开始阶段时进入弃牌堆。' }),
  e({ id: 'giveaway', name: '抽奖转发', count: 1, topic: '社群',
    up: '个人影响力+1。从你开始，每位玩家依次抽一张行动牌。', down: '抽两张行动牌。' }),
  e({ id: 'weird_scene', name: '现场发生迷惑行为', count: 1, topic: '活动',
    up: '如果所有玩家个人影响力均非负，社群规模+3，否则社群规模-2。',
    down: '如果没有玩家个人影响力为0，社群规模-1，否则社群规模-2。' }),
  e({ id: 'nikenme', name: '二轩目直播', count: 1, topic: '官方',
    up: '重复发动上一张进入弃牌堆的事件牌的效果。', down: '你抽一张事件牌并立即正向打出。' }),

  // ── 连锁事件 ─────────────────────────────────────
  e({ id: 'popularity_poll', name: '人气投票', count: 7, topic: '活动', shape: 'chain',
    up: '社群规模+X，X为连锁事件区中「人气投票」的张数+1。将本牌置入连锁事件区。',
    down: '社群规模-X，X为连锁事件区中「人气投票」的张数+1。将本牌置入连锁事件区。' }),
  e({ id: 'blooming', name: '遍地开花', count: 4, topic: '活动', shape: 'chain',
    up: '社群规模+1。将本牌置入连锁事件区。当本事件进入连锁事件区时，若连锁事件区中其他「遍地开花」数量大于等于2，则社群规模+5，在这之后所有玩家摸牌阶段额外摸一张行动牌。',
    down: '以该方向打出时本牌直接进入弃牌堆且无任何效果。' }),

  // ── 比较特殊 ─────────────────────────────────────
  e({ id: 'crackdown', name: '扫黄打非', count: 1, topic: '社会',
    up: '指定一名玩家，其个人影响力-5并跳过他的下个回合。社群规模-1。本事件牌在该玩家的下回合开始阶段时发动跳过效果并进入弃牌堆。',
    down: '所有玩家个人影响力+1，社群规模+2。' }),
  e({ id: 'withdrawn', name: '自闭', count: 1, topic: '个人',
    up: '直到你的下个回合开始，你不受任何行动牌和事件牌的效果影响。本事件牌在你的下回合开始阶段时进入弃牌堆。',
    down: '弃置任意数量张手牌，然后抽等量行动牌。' }),

  // ── 无向事件 ─────────────────────────────────────
  e({ id: 'sick', name: '大病一场', count: 1, topic: '个人', forced: true,
    up: '立即结束你的当前回合。本事件牌在你的下回合开始阶段时进入弃牌堆。本事件牌在抽到时必须立即打出，无视任何牌效果。' }),
  e({ id: 'cultural_confidence', name: '文化自信', count: 1, topic: '社会',
    up: '社群规模成为0。' }),
  e({ id: 'translation', name: '翻译修订', count: 1, topic: '社群',
    up: '进行等同于玩家数量次真假判定：若判定结果为真的次数更多或刚好持平，个人影响力+2，社群规模-1；若判定结果为假的次数更多，个人影响力-3。' }),
  e({ id: 'recession', name: '经济寒冬', count: 1, topic: '社会',
    up: '每位玩家弃两张手牌。' }),
  e({ id: 'calm', name: '大环境沉稳', count: 1, topic: '社会',
    up: '社群规模+3。' }),
  e({ id: 'generation_gap', name: '青黄不接', count: 1, topic: '社群',
    up: '直到你的下个回合开始，所有玩家都不能在回合开始时抽行动牌。本事件牌在你的下个回合开始阶段时进入弃牌堆。' }),
  e({ id: 'long_holiday', name: '放长假', count: 1, topic: '社会',
    up: '每位玩家可以弃置一张手牌，如此做的玩家个人影响力+1。' }),
  e({ id: 'loan', name: '得到借款', count: 1, topic: '个人',
    up: '你抽两张行动牌。在你的下一个回合结束前，你的手牌上限+2。跳过你下一回合的抽牌阶段。本事件牌在你的下回合开始阶段时进入弃牌堆。' }),
  e({ id: 'mass_exodus', name: '大规模退坑', count: 1, topic: '社群',
    up: '所有玩家个人影响力+2。社群规模-5。' }),
  e({ id: 'lottery', name: '彩票中奖', count: 1, topic: '个人',
    up: '抽四张行动牌，个人影响力+2。跳过你本回合的弃牌阶段。' }),
  e({ id: 'restless', name: '大环境浮躁', count: 1, topic: '社会',
    up: '社群规模-3。' }),
  e({ id: 'finale', name: '连载完结', count: 1, topic: '官方',
    up: '本轮内官作牌失去效果。' }),
  e({ id: 'trend', name: '大势所趋', count: 1, topic: '社群',
    up: '社群规模大于0则+3，小于0则-3，等于0则不变。' }),
  e({ id: 'new_title', name: '发布新作', count: 1, topic: '官方',
    up: '抽一张官作牌，用其替换当前生效的官作牌（被替换的官作牌立即进入官作弃牌堆）。' }),
];

export const EVENT_TOPIC_COLOR: Record<EventCardDef['topic'], string> = {
  社会: '#5b6b8c',
  社群: '#3f8f7a',
  创作: '#c2703d',
  活动: '#c24a5a',
  官方: '#8a5cc2',
  个人: '#b0913a',
};
